### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by marlonnardi** [RRUZ/delphi-preview-handler#10]
Assinatura do problema:
  Nome do Evento de Problema:	APPCRASH
  Nome do Aplicativo:	prevhost.exe
  Versão do Aplicativo:	6.1.7601.17562
  Carimbo de Data/Hora do Aplicativo:	4d5dee89
  Nome do Módulo de Falhas:	KERNELBASE.dll
  Versão do Módulo de Falhas:	6.1.7601.18939
  Carimbo de Data/Hora do Módulo de Falhas:	55afd8e7
  Código de Exceção:	0eedfade
  Deslocamento de Exceção:	0000c42d
  Versão do sistema operacional:	6.1.7601.2.1.0.256.48
  Identificação da Localidade:	1046
  Informações Adicionais 1:	c8e3
  Informações Adicionais 2:	c8e314b651a3aeca770854d808985349
  Informações Adicionais 3:	5d16
  Informações Adicionais 4:	5d164243fa07f496715f8df6a52af417

Leia nossa declaração de privacidade online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0416

Se a declaração de privacidade online não estiver disponível, leia nossa declaração de privacidade offline:
  C:\Windows\system32\pt-BR\erofflps.txt

**Comment by RRUZ** [comment]
Hi, can you please describe the steps to reproduce this issue? Also check if exist a bug report on this location %AppData%\EurekaLab s.a.s\EurekaLog\Bug Reports\DelphiPreviewHandler.dll and attach the file to this issue if exist.

**Comment by marlonnardi** [comment]
*had many open explorer + - 20, this error occurred when I closed all explorer.

*in the given folder does not have anything.

**Comment by RRUZ** [comment]
OK, thanks I will try to reproduce the issue. Please let me know if happens again in under another circumstances.

**Comment by RRUZ** [comment]
Hi Marlon, I just uploaded a new version 1.3.6.6.

**Comment by marlonnardi** [comment]
thanks, I'll update
