### ISSUE TITLE
Previewing files in zipped folders

### ISSUE THREAD

**Issue by michaelthuma** [RRUZ/delphi-preview-handler#12]
Hallo. Today I installed the lastest version of the previewhandler. Great work, very impressive.

One question is left. Is it planned to preview the content of files in zipped folders. That worked with the version I  used until today. It's not vital. I simply installed a ram-disk and extract the files to this location. Just wanted to know if this feature should be there or is simply no longer available. Maybe I am doing something wrong.

**Comment by RRUZ** [comment]
Hi MIchael, thanks for your words. About the zip preview soory, but I don't have any plans to include this feature on this project.

**Comment by michaelthuma** [comment]
Thank you. Just in order get things straight. I am not talking about a functionality to be added. For some reasons in former versions when navigating zip archives in the Explorer the preview showed up. Now that does not work anymore. Again - no problem for me at all. Let's say the Explorer does not invoke the handler I think... in Win 8.1.

**Comment by RRUZ** [comment]
Michael, maybe the .zip preview handler was installed for a third-party App.

**Comment by michaelthuma** [comment]
Ah! Ok. Thank's a lot.
