### ISSUE TITLE
64bit version

### ISSUE THREAD

**Issue by eagleeyez** [RRUZ/delphi-preview-handler#22]
Hi,

Please can you compile a x64 version compatible with Windows 10, I tried to download the required files to do it myself but I lack the knowledge about the additional libraries and how to add them to the IDE.

Thank you.

**Comment by RRUZ** [comment]
Please check the [release page](https://github.com/RRUZ/delphi-preview-handler/releases), the installer includes the preview handler for x86 and x64.
